name: ci:test:docs
on:
  pull_request:
    paths:
      - 'docs/**'
  push:
    paths:
      - 'docs/**'
defaults:
  run:
    working-directory: docs

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: install
        run:  bundle install
      - name: build
        run: bundle exec rake build
