name: ci:test
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install Invenio-CLI
        run: |
          python --version
          which pip
          pip install invenio-cli
      - name: Check Requirements
        run: invenio-cli check-requirements
      # - name: Generate dependencies
      #   run: |
      #     invenio-cli packages lock --pre --dev
      #     invenio-cli install --pre --development
