name: ci:test:docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout current state"
        uses: actions/checkout@v2
      - name: "Save Ruby version to env"
        run: echo "RUBY_VERSION=$(cat './docs/.ruby-version')" >> ${GITHUB_ENV}
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: ./docs
      - name: "Build the documentation"
        run: bundle exec rake build
        working-directory: ./docs
      - name: "Test the documentation"
        run: bundle exec rake test
        working-directory: ./docs
