name: ci:test:docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: ./docs
          bundler-cache: true
      - name: install
        working-directory: ./docs
        run:  bundle install
      - name: install
        working-directory: ./docs
        run:  bundle exec rake build
      - name: install
        working-directory: ./docs
        run:  bundle exec rake test
