name: ci:test
on: [push, pull_request]

jobs:
  test:
    env:
      PYTHON_VERSION: '3.7.9'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Python $PYTHON_VERSION
        uses: actions/setup-python@v2
        with:
          python-version: $PYTHON_VERSION
      - name: Check Requirements
        run: invenio-cli check-requirements
      # - name: Generate dependencies
      #   run: |
      #     invenio-cli packages lock --pre --dev
      #     invenio-cli install --pre --development
