name: ci:test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    strategy:
      matrix:
          cache-service: [redis5]
          search-service: [opensearch2]
          db-service: [postgresql10 ]

          include:
          - db-service: postgresql10
            DB_EXTRAS: "postgresql"
          - search-service: opensearch2
            SEARCH_EXTRAS: "opensearch2"
          - cache-service: redis 
            SEARCH_EXTRAS: "redis5"

    env:
      CACHE: ${{ matrix.cache-service }}
      DB: ${{ matrix.db-service }}
      SEARCH: ${{ matrix.search-service }}
      EXTRAS: tests
    steps:
      - name: "Checkout current state"
        uses: actions/checkout@v2
      - name: "Save Python and Node versions to env"
        run: |
          echo "PYTHON_VERSION=$(cat '.python-version')" >> ${GITHUB_ENV}
          echo "NODE_VERSION=$(cat '.nvmrc')" >> ${GITHUB_ENV}
      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: "Set up Node"
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: "Install invenio-cli"
        run: |
          pip install --no-cache-dir --upgrade pip invenio-cli pipenv
          pip list
      - name: "Install XMLSec1 Dependency for Ultraviolet SAML"
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libxml2-dev libxmlsec1-dev
      - name: "Setup mandatory files"
        run: |
          echo -e "[cli]\nproject_dir = "$PWD"\nservices_setup = False" >> .invenio.private
          echo -e FLASK_SECRET_KEY="some random value" >> .env
      - name: "Install project dependencies"
        run: |
          pipenv run python3.8 -m pip install 'setuptools~=57.5.0'
          invenio-cli packages lock --pre --dev
          invenio-cli install --pre --dev
      # - name: Start services and app
         # run: |
          # invenio-cli services start
          # invenio-cli run &
      - name: "Run tests"
        run: |
          pipenv install --dev
          E2E=no pipenv run pytest -p no:cacheprovider
