name: ci:test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout current state"
        uses: actions/checkout@v2
      - name: "Save Python and Node versions to env"
        run: |
          echo "PYTHON_VERSION=$(cat '.python-version')" >> ${GITHUB_ENV}
          echo "NODE_VERSION=$(cat '.nvmrc')" >> ${GITHUB_ENV}
      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: "Set up Node"
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: "Install invenio-cli"
        run: |
          pip install --no-cache-dir --upgrade pip setuptools wheel
          pip install --no-cache-dir --quiet invenio-cli
          pip list
      - name: "Check project requirements"
        run: invenio-cli check-requirements
      - name: "Setup mandatory files"
        run: |
          echo "[cli]\nproject_dir = "$PWD"\nservices_setup = False" >> .invenio.private
          echo FLASK_SECRET_KEY="some random value" >> .env
      - name: "Install project dependencies"
        run: |
          pipenv run python3.8 -m pip install 'setuptools~=57.5.0'
          invenio-cli packages lock --pre --dev
          invenio-cli install --pre --dev
      - name: "Run tests"
        run: |
          sh ./run_tests.sh
