name: ci:test:docs
on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'docs/**'
  push:
    paths:
      - '.github/workflows/**'
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: ./docs
          bundler-cache: true
      - name: install
        working-directory: ./docs
        run:  bundle install
      - name: install
        working-directory: ./docs
        run:  bundle exec rake build
      - name: install
        working-directory: ./docs
        run:  bundle exec rake test
